/**
 * Professional cover-typography presets.
 *
 * Each entry is a complete typographic system rather than a font choice: the
 * relationship between title, subtitle, author and series line is what makes a
 * cover read as professionally set, so a preset patches every role at once —
 * face, weight, tracking, case, colour, effects and vertical placement.
 *
 * Horizontal placement (`x`, `width`) is deliberately left alone: that is the
 * designer's composition against their own photograph. The one exception is a
 * style whose whole idea is the position — Graphic Novel turns the title down
 * the right-hand edge, which is meaningless without the geometry.
 */
import type { CoverDoc, LayerRole, TextLayer } from "./types";

type RolePatch = Partial<TextLayer>;

export type CoverStyle = {
  id: string;
  name: string;
  genre: string;
  description: string;
  /** Wash applied under the type so the preset's contrast holds up. */
  scrim?: Partial<Pick<CoverDoc, "scrim" | "scrimColor" | "scrimOpacity">>;
  roles: Partial<Record<LayerRole, RolePatch>>;
};

/** Clears effects a previous preset may have switched on. */
const CLEAN: RolePatch = {
  italic: false,
  strokeWidth: 0,
  shadowEnabled: false,
  bandEnabled: false,
  rules: "none",
  rotation: 0,
  opacity: 1,
};

const IVORY = "#F4EFE6";
const GOLD = "#D9B96A";
const BONE = "#E7E3DB";

export const COVER_STYLES: CoverStyle[] = [
  {
    id: "literary-classic",
    name: "Literary Classic",
    genre: "Literary fiction",
    description:
      "Wide-tracked serif caps between hairline rules. The upmarket look of a prize shortlist.",
    scrim: { scrim: "solid", scrimColor: "#000000", scrimOpacity: 0.32 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "cormorant",
        weight: 600,
        size: 2.5,
        y: 0.1,
        letterSpacing: 0.36,
        transform: "uppercase",
        color: BONE,
        lineHeight: 1.2,
      },
      title: {
        ...CLEAN,
        fontId: "cormorant",
        weight: 600,
        size: 9.5,
        y: 0.2,
        lineHeight: 1.1,
        letterSpacing: 0.14,
        transform: "uppercase",
        color: IVORY,
        rules: "both",
        ruleThickness: 2.5,
        ruleLength: 0.62,
        ruleGap: 46,
      },
      subtitle: {
        ...CLEAN,
        fontId: "cormorant",
        weight: 400,
        italic: true,
        size: 4,
        y: 0.52,
        letterSpacing: 0.03,
        transform: "none",
        color: BONE,
      },
      author: {
        ...CLEAN,
        fontId: "cormorant",
        weight: 600,
        size: 4,
        y: 0.87,
        letterSpacing: 0.3,
        transform: "uppercase",
        color: IVORY,
      },
    },
  },
  {
    id: "modern-minimal",
    name: "Modern Minimal",
    genre: "Contemporary / design",
    description:
      "Hairline sans, generous tracking, nothing decorative. Lets a strong photograph carry the cover.",
    scrim: { scrim: "none", scrimColor: "#000000", scrimOpacity: 0.3 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "raleway",
        weight: 400,
        size: 2.4,
        y: 0.11,
        letterSpacing: 0.4,
        transform: "uppercase",
        color: "#FFFFFF",
      },
      title: {
        ...CLEAN,
        fontId: "raleway",
        weight: 200,
        size: 10,
        y: 0.21,
        lineHeight: 1.15,
        letterSpacing: 0.14,
        transform: "uppercase",
        color: "#FFFFFF",
      },
      subtitle: {
        ...CLEAN,
        fontId: "raleway",
        weight: 400,
        size: 3.4,
        y: 0.55,
        letterSpacing: 0.16,
        transform: "uppercase",
        color: "#FFFFFF",
      },
      author: {
        ...CLEAN,
        fontId: "raleway",
        weight: 700,
        size: 3.6,
        y: 0.88,
        letterSpacing: 0.32,
        transform: "uppercase",
        color: "#FFFFFF",
      },
    },
  },
  {
    id: "thriller",
    name: "Thriller",
    genre: "Thriller / crime",
    description:
      "Condensed gothic caps stacked tight, with a soft drop shadow to lift them off a dark photo.",
    scrim: { scrim: "both", scrimColor: "#000000", scrimOpacity: 0.55 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "oswald",
        weight: 500,
        size: 2.6,
        y: 0.09,
        letterSpacing: 0.34,
        transform: "uppercase",
        color: "#E4372E",
      },
      title: {
        ...CLEAN,
        fontId: "oswald",
        weight: 700,
        size: 14,
        y: 0.16,
        lineHeight: 0.94,
        letterSpacing: 0.01,
        transform: "uppercase",
        color: "#FFFFFF",
        shadowEnabled: true,
        shadowBlur: 26,
        shadowOffsetX: 0,
        shadowOffsetY: 6,
        shadowColor: "#000000",
        shadowOpacity: 0.7,
      },
      subtitle: {
        ...CLEAN,
        fontId: "oswald",
        weight: 300,
        size: 3.4,
        y: 0.56,
        letterSpacing: 0.22,
        transform: "uppercase",
        color: "#D6DCE5",
      },
      author: {
        ...CLEAN,
        fontId: "oswald",
        weight: 500,
        size: 4.6,
        y: 0.86,
        letterSpacing: 0.18,
        transform: "uppercase",
        color: "#FFFFFF",
      },
    },
  },
  {
    id: "suspense-block",
    name: "Suspense Block",
    genre: "Psychological suspense",
    description:
      "Poster caps on a solid band. Guaranteed legibility at thumbnail size, however busy the image.",
    scrim: { scrim: "none", scrimColor: "#000000", scrimOpacity: 0.3 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 800,
        size: 2.3,
        y: 0.08,
        letterSpacing: 0.36,
        transform: "uppercase",
        color: "#FFFFFF",
      },
      title: {
        ...CLEAN,
        fontId: "bebas",
        weight: 400,
        size: 15,
        y: 0.17,
        lineHeight: 0.9,
        letterSpacing: 0.02,
        transform: "uppercase",
        color: "#FFFFFF",
        bandEnabled: true,
        bandColor: "#0B0B0C",
        bandOpacity: 0.88,
        bandPadX: 26,
        bandPadY: 16,
      },
      subtitle: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 600,
        size: 3,
        y: 0.58,
        letterSpacing: 0.24,
        transform: "uppercase",
        color: "#FFFFFF",
        bandEnabled: true,
        bandColor: "#0B0B0C",
        bandOpacity: 0.8,
        bandPadX: 34,
        bandPadY: 22,
      },
      author: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 800,
        size: 4.4,
        y: 0.85,
        letterSpacing: 0.16,
        transform: "uppercase",
        color: "#FFFFFF",
      },
    },
  },
  {
    id: "epic-fantasy",
    name: "Epic Fantasy",
    genre: "Fantasy / epic",
    description:
      "Inscriptional Roman caps in antique gold with a dark outline — the standard for high fantasy.",
    scrim: { scrim: "both", scrimColor: "#0A0A12", scrimOpacity: 0.5 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "cinzel",
        weight: 400,
        size: 2.6,
        y: 0.09,
        letterSpacing: 0.3,
        transform: "uppercase",
        color: BONE,
      },
      title: {
        ...CLEAN,
        fontId: "cinzel",
        weight: 900,
        size: 11,
        y: 0.18,
        lineHeight: 1.08,
        letterSpacing: 0.06,
        transform: "uppercase",
        color: GOLD,
        strokeWidth: 3,
        strokeColor: "#22190B",
        shadowEnabled: true,
        shadowBlur: 30,
        shadowOffsetX: 0,
        shadowOffsetY: 6,
        shadowColor: "#000000",
        shadowOpacity: 0.65,
      },
      subtitle: {
        ...CLEAN,
        fontId: "cinzel",
        weight: 400,
        size: 3.4,
        y: 0.52,
        letterSpacing: 0.2,
        transform: "uppercase",
        color: BONE,
      },
      author: {
        ...CLEAN,
        fontId: "cinzel",
        weight: 700,
        size: 4.2,
        y: 0.86,
        letterSpacing: 0.2,
        transform: "uppercase",
        color: GOLD,
      },
    },
  },
  {
    id: "romance-script",
    name: "Romance Script",
    genre: "Romance",
    description:
      "A large calligraphic title over a small tracked sans byline. Warm, soft, unmistakably romance.",
    scrim: { scrim: "bottom", scrimColor: "#2B1218", scrimOpacity: 0.45 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 600,
        size: 2.4,
        y: 0.1,
        letterSpacing: 0.34,
        transform: "uppercase",
        color: "#F6E7E4",
      },
      title: {
        ...CLEAN,
        fontId: "great-vibes",
        weight: 400,
        size: 15,
        y: 0.19,
        lineHeight: 1,
        letterSpacing: 0,
        transform: "none",
        color: "#FFF6F2",
        shadowEnabled: true,
        shadowBlur: 24,
        shadowOffsetX: 0,
        shadowOffsetY: 4,
        shadowColor: "#3A1C22",
        shadowOpacity: 0.5,
      },
      subtitle: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 400,
        size: 3.1,
        y: 0.56,
        letterSpacing: 0.24,
        transform: "uppercase",
        color: "#F6E7E4",
      },
      author: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 600,
        size: 4,
        y: 0.87,
        letterSpacing: 0.26,
        transform: "uppercase",
        color: "#FFF6F2",
      },
    },
  },
  {
    id: "book-club",
    name: "Book Club",
    genre: "Women's fiction",
    description:
      "Italic display serif with an airy sans byline — the shelf language of upmarket book-club fiction.",
    scrim: { scrim: "bottom", scrimColor: "#1B1A17", scrimOpacity: 0.4 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "josefin",
        weight: 400,
        size: 2.5,
        y: 0.1,
        letterSpacing: 0.32,
        transform: "uppercase",
        color: BONE,
      },
      title: {
        ...CLEAN,
        fontId: "playfair",
        weight: 700,
        italic: true,
        size: 12,
        y: 0.2,
        lineHeight: 1.02,
        letterSpacing: 0,
        transform: "none",
        color: "#FFFFFF",
      },
      subtitle: {
        ...CLEAN,
        fontId: "josefin",
        weight: 300,
        size: 3.4,
        y: 0.55,
        letterSpacing: 0.18,
        transform: "uppercase",
        color: BONE,
      },
      author: {
        ...CLEAN,
        fontId: "josefin",
        weight: 600,
        size: 4,
        y: 0.87,
        letterSpacing: 0.26,
        transform: "uppercase",
        color: "#FFFFFF",
      },
    },
  },
  {
    id: "sci-fi",
    name: "Sci-Fi Signal",
    genre: "Science fiction",
    description:
      "Monospaced caps at extreme tracking, split by a thin rule. Cold, technical, near-future.",
    scrim: { scrim: "both", scrimColor: "#020A12", scrimOpacity: 0.5 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "space-mono",
        weight: 400,
        size: 2.2,
        y: 0.09,
        letterSpacing: 0.45,
        transform: "uppercase",
        color: "#7FE7F5",
      },
      title: {
        ...CLEAN,
        fontId: "space-mono",
        weight: 700,
        size: 9,
        y: 0.19,
        lineHeight: 1.16,
        letterSpacing: 0.18,
        transform: "uppercase",
        color: "#EAF6FF",
        rules: "below",
        ruleThickness: 2,
        ruleLength: 0.72,
        ruleGap: 44,
      },
      subtitle: {
        ...CLEAN,
        fontId: "space-mono",
        weight: 400,
        size: 2.9,
        y: 0.56,
        letterSpacing: 0.3,
        transform: "uppercase",
        color: "#9FB6C6",
      },
      author: {
        ...CLEAN,
        fontId: "space-mono",
        weight: 700,
        size: 3.6,
        y: 0.87,
        letterSpacing: 0.3,
        transform: "uppercase",
        color: "#EAF6FF",
      },
    },
  },
  {
    id: "horror",
    name: "Horror",
    genre: "Horror / true crime",
    description:
      "Compressed impact caps, hard black outline, distressed typewriter support type.",
    scrim: { scrim: "solid", scrimColor: "#000000", scrimOpacity: 0.45 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "special-elite",
        weight: 400,
        size: 2.6,
        y: 0.09,
        letterSpacing: 0.24,
        transform: "uppercase",
        color: "#C9C4BC",
      },
      title: {
        ...CLEAN,
        fontId: "anton",
        weight: 400,
        size: 14,
        y: 0.17,
        lineHeight: 0.92,
        letterSpacing: 0.01,
        transform: "uppercase",
        color: "#F2EDE6",
        strokeWidth: 4,
        strokeColor: "#0A0A0A",
        shadowEnabled: true,
        shadowBlur: 34,
        shadowOffsetX: 0,
        shadowOffsetY: 8,
        shadowColor: "#000000",
        shadowOpacity: 0.8,
      },
      subtitle: {
        ...CLEAN,
        fontId: "special-elite",
        weight: 400,
        size: 3.2,
        y: 0.57,
        letterSpacing: 0.16,
        transform: "uppercase",
        color: "#B9302B",
      },
      author: {
        ...CLEAN,
        fontId: "special-elite",
        weight: 400,
        size: 4,
        y: 0.86,
        letterSpacing: 0.18,
        transform: "uppercase",
        color: "#F2EDE6",
      },
    },
  },
  {
    id: "nonfiction-authority",
    name: "Authority",
    genre: "Business / self-help",
    description:
      "Heavy geometric caps, a coloured rule under the title, and a clean byline. Reads as expertise.",
    scrim: { scrim: "solid", scrimColor: "#0B1B2B", scrimOpacity: 0.4 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 600,
        size: 2.4,
        y: 0.1,
        letterSpacing: 0.3,
        transform: "uppercase",
        color: "#5AC8C0",
      },
      title: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 800,
        size: 11.5,
        y: 0.19,
        lineHeight: 1.02,
        letterSpacing: -0.01,
        transform: "uppercase",
        color: "#FFFFFF",
        rules: "below",
        ruleThickness: 5,
        ruleLength: 0.28,
        ruleGap: 40,
      },
      subtitle: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 400,
        size: 3.4,
        y: 0.58,
        letterSpacing: 0.04,
        transform: "none",
        color: "#D4E2EC",
      },
      author: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 600,
        size: 4,
        y: 0.87,
        letterSpacing: 0.2,
        transform: "uppercase",
        color: "#FFFFFF",
      },
    },
  },
  {
    id: "memoir",
    name: "Memoir",
    genre: "Memoir / essays",
    description:
      "Quiet Baskerville with a lot of air around it. Personal, considered, never shouty.",
    scrim: { scrim: "bottom", scrimColor: "#1A1714", scrimOpacity: 0.42 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 600,
        size: 2.2,
        y: 0.11,
        letterSpacing: 0.36,
        transform: "uppercase",
        color: BONE,
      },
      title: {
        ...CLEAN,
        fontId: "baskerville",
        weight: 700,
        size: 9.5,
        y: 0.21,
        lineHeight: 1.18,
        letterSpacing: 0.01,
        transform: "none",
        color: "#FBF7F0",
      },
      subtitle: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 400,
        size: 3,
        y: 0.56,
        letterSpacing: 0.2,
        transform: "uppercase",
        color: BONE,
      },
      author: {
        ...CLEAN,
        fontId: "baskerville",
        weight: 400,
        size: 3.8,
        y: 0.88,
        letterSpacing: 0.24,
        transform: "uppercase",
        color: "#FBF7F0",
      },
    },
  },
  {
    id: "historical",
    name: "Historical",
    genre: "Historical fiction",
    description:
      "Old-style Garamond framed top and bottom by rules — period-appropriate without costume.",
    scrim: { scrim: "solid", scrimColor: "#241A10", scrimOpacity: 0.38 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "garamond",
        weight: 500,
        size: 2.5,
        y: 0.1,
        letterSpacing: 0.32,
        transform: "uppercase",
        color: "#E4D3B0",
      },
      title: {
        ...CLEAN,
        fontId: "garamond",
        weight: 600,
        size: 10.5,
        y: 0.2,
        lineHeight: 1.1,
        letterSpacing: 0.08,
        transform: "uppercase",
        color: "#FAF3E6",
        rules: "above",
        ruleThickness: 2,
        ruleLength: 0.4,
        ruleGap: 44,
      },
      subtitle: {
        ...CLEAN,
        fontId: "garamond",
        weight: 400,
        size: 3.8,
        y: 0.54,
        letterSpacing: 0.06,
        transform: "none",
        color: "#E4D3B0",
      },
      author: {
        ...CLEAN,
        fontId: "garamond",
        weight: 500,
        size: 4,
        y: 0.87,
        letterSpacing: 0.28,
        transform: "uppercase",
        color: "#FAF3E6",
      },
    },
  },
  {
    id: "vintage-pulp",
    name: "Vintage Pulp",
    genre: "Retro / pulp",
    description:
      "Fat didone title with a hard offset shadow, set in cream. Mid-century paperback energy.",
    scrim: { scrim: "solid", scrimColor: "#1B0F08", scrimOpacity: 0.35 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "special-elite",
        weight: 400,
        size: 2.6,
        y: 0.1,
        letterSpacing: 0.2,
        transform: "uppercase",
        color: "#F0D9A8",
      },
      title: {
        ...CLEAN,
        fontId: "abril",
        weight: 400,
        size: 13,
        y: 0.18,
        lineHeight: 1,
        letterSpacing: 0,
        transform: "uppercase",
        color: "#F7ECD5",
        shadowEnabled: true,
        shadowBlur: 0,
        shadowOffsetX: 5,
        shadowOffsetY: 6,
        shadowColor: "#B3341F",
        shadowOpacity: 1,
      },
      subtitle: {
        ...CLEAN,
        fontId: "special-elite",
        weight: 400,
        size: 3.2,
        y: 0.56,
        letterSpacing: 0.12,
        transform: "uppercase",
        color: "#F0D9A8",
      },
      author: {
        ...CLEAN,
        fontId: "abril",
        weight: 400,
        size: 4.4,
        y: 0.86,
        letterSpacing: 0.06,
        transform: "uppercase",
        color: "#F7ECD5",
      },
    },
  },
  {
    id: "cozy-mystery",
    name: "Cozy Mystery",
    genre: "Cozy mystery",
    description:
      "Deco geometric title over a light script byline. Friendly, series-ready, easy at thumbnail size.",
    scrim: { scrim: "bottom", scrimColor: "#14231F", scrimOpacity: 0.4 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "josefin",
        weight: 600,
        size: 2.6,
        y: 0.09,
        letterSpacing: 0.3,
        transform: "uppercase",
        color: "#FFD9A0",
      },
      title: {
        ...CLEAN,
        fontId: "josefin",
        weight: 600,
        size: 12,
        y: 0.18,
        lineHeight: 1.02,
        letterSpacing: 0.06,
        transform: "uppercase",
        color: "#FFFFFF",
        shadowEnabled: true,
        shadowBlur: 20,
        shadowOffsetX: 0,
        shadowOffsetY: 3,
        shadowColor: "#0B1A16",
        shadowOpacity: 0.5,
      },
      subtitle: {
        ...CLEAN,
        fontId: "parisienne",
        weight: 400,
        size: 5,
        y: 0.55,
        letterSpacing: 0,
        transform: "none",
        color: "#FFD9A0",
      },
      author: {
        ...CLEAN,
        fontId: "josefin",
        weight: 400,
        size: 4,
        y: 0.87,
        letterSpacing: 0.26,
        transform: "uppercase",
        color: "#FFFFFF",
      },
    },
  },
  {
    id: "young-adult",
    name: "Young Adult",
    genre: "YA / crossover",
    description:
      "Oversized tight-set sans that fills the width. Built to survive a 60px store thumbnail.",
    scrim: { scrim: "both", scrimColor: "#120C1F", scrimOpacity: 0.48 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 800,
        size: 2.6,
        y: 0.09,
        letterSpacing: 0.32,
        transform: "uppercase",
        color: "#B79BFF",
      },
      title: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 800,
        size: 15,
        y: 0.16,
        lineHeight: 0.94,
        letterSpacing: -0.02,
        transform: "uppercase",
        color: "#FFFFFF",
      },
      subtitle: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 400,
        size: 3.2,
        y: 0.58,
        letterSpacing: 0.22,
        transform: "uppercase",
        color: "#DDD3F5",
      },
      author: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 600,
        size: 4.2,
        y: 0.86,
        letterSpacing: 0.2,
        transform: "uppercase",
        color: "#FFFFFF",
      },
    },
  },
  {
    id: "poetry",
    name: "Poetry",
    genre: "Poetry / quiet literary",
    description:
      "Light lower-case serif with open leading and a single hairline. Restraint is the whole design.",
    scrim: { scrim: "solid", scrimColor: "#0E0F12", scrimOpacity: 0.3 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "cormorant",
        weight: 300,
        size: 2.4,
        y: 0.11,
        letterSpacing: 0.3,
        transform: "lowercase",
        color: BONE,
      },
      title: {
        ...CLEAN,
        fontId: "cormorant",
        weight: 300,
        size: 9,
        y: 0.22,
        lineHeight: 1.3,
        letterSpacing: 0.04,
        transform: "lowercase",
        color: "#F7F4EF",
        rules: "below",
        ruleThickness: 1.5,
        ruleLength: 0.22,
        ruleGap: 56,
      },
      subtitle: {
        ...CLEAN,
        fontId: "cormorant",
        weight: 300,
        italic: true,
        size: 3.6,
        y: 0.6,
        letterSpacing: 0.04,
        transform: "lowercase",
        color: BONE,
      },
      author: {
        ...CLEAN,
        fontId: "cormorant",
        weight: 400,
        size: 3.6,
        y: 0.88,
        letterSpacing: 0.3,
        transform: "lowercase",
        color: "#F7F4EF",
      },
    },
  },

  /* ----------------------------------------------------------------
     Author-brand layouts.

     Everything above puts the title at the top. On the commercial
     shelf — Sandford, Cornwell, Patterson and the Kindle charts that
     imitate them — the *author* is the product, so the name takes the
     top third at title scale and the title itself drops to the foot of
     the cover. These presets move the roles accordingly.
     ---------------------------------------------------------------- */

  {
    id: "author-brand",
    name: "Author Brand",
    genre: "Commercial thriller",
    description:
      "The name sells the book: author across the top at title scale, series line beneath it, title dropped to the foot in heavy caps.",
    scrim: { scrim: "both", scrimColor: "#050B12", scrimOpacity: 0.55 },
    roles: {
      author: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 800,
        size: 9,
        y: 0.045,
        lineHeight: 0.98,
        letterSpacing: 0.01,
        transform: "uppercase",
        color: "#FFFFFF",
      },
      series: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 600,
        size: 2.7,
        y: 0.155,
        letterSpacing: 0.26,
        transform: "uppercase",
        color: "#F2913D",
      },
      title: {
        ...CLEAN,
        fontId: "anton",
        weight: 400,
        size: 15,
        y: 0.62,
        lineHeight: 0.92,
        letterSpacing: 0,
        transform: "uppercase",
        color: "#FFFFFF",
        shadowEnabled: true,
        shadowBlur: 24,
        shadowOffsetX: 0,
        shadowOffsetY: 5,
        shadowColor: "#000000",
        shadowOpacity: 0.6,
      },
      subtitle: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 600,
        size: 2.8,
        y: 0.93,
        letterSpacing: 0.26,
        transform: "uppercase",
        color: "#D7DEE6",
      },
    },
  },
  {
    id: "domestic-suspense",
    name: "Domestic Suspense",
    genre: "Domestic / psychological",
    description:
      "Stacked caps tracked out until each line fills the width, softened by a script aside. The look of the book-club thriller table.",
    scrim: { scrim: "top", scrimColor: "#2A2430", scrimOpacity: 0.3 },
    roles: {
      title: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 800,
        size: 11,
        y: 0.06,
        lineHeight: 1.02,
        letterSpacing: 0.22,
        transform: "uppercase",
        color: "#FFFFFF",
      },
      subtitle: {
        ...CLEAN,
        fontId: "parisienne",
        weight: 400,
        size: 5.2,
        y: 0.4,
        letterSpacing: 0,
        transform: "none",
        color: "#FFFFFF",
      },
      author: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 600,
        size: 5,
        y: 0.8,
        letterSpacing: 0.3,
        transform: "uppercase",
        color: "#FFFFFF",
      },
      series: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 400,
        size: 2.2,
        y: 0.9,
        letterSpacing: 0.3,
        transform: "uppercase",
        color: "#F0E9EE",
      },
    },
  },
  {
    id: "true-crime",
    name: "True Crime",
    genre: "True crime / investigation",
    description:
      "Blood-red caps at wide tracking with a long tracked deck beneath, over a bleak photograph. Documentary, not lurid.",
    scrim: { scrim: "solid", scrimColor: "#0E1418", scrimOpacity: 0.18 },
    roles: {
      title: {
        ...CLEAN,
        fontId: "baskerville",
        weight: 400,
        size: 8,
        y: 0.13,
        lineHeight: 1.55,
        letterSpacing: 0.32,
        transform: "uppercase",
        color: "#B32217",
      },
      subtitle: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 400,
        size: 2.5,
        y: 0.55,
        lineHeight: 2.1,
        letterSpacing: 0.2,
        transform: "uppercase",
        color: "#4C5A66",
      },
      author: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 700,
        size: 6.4,
        y: 0.82,
        letterSpacing: 0.12,
        transform: "uppercase",
        color: "#FFFFFF",
      },
      series: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 400,
        size: 2.1,
        y: 0.92,
        letterSpacing: 0.24,
        transform: "uppercase",
        color: "#C3CDD6",
      },
    },
  },
  {
    id: "red-alert",
    name: "Red Alert",
    genre: "Action / suspense",
    description:
      "Four short lines of scarlet caps packed edge to edge under a small white byline. Loud at any size, which is the point.",
    scrim: { scrim: "solid", scrimColor: "#000000", scrimOpacity: 0.35 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 600,
        size: 2.4,
        y: 0.05,
        letterSpacing: 0.24,
        transform: "uppercase",
        color: "#E8622A",
      },
      author: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 600,
        size: 4.6,
        y: 0.11,
        letterSpacing: 0.16,
        transform: "uppercase",
        color: "#FFFFFF",
      },
      title: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 800,
        size: 15,
        y: 0.24,
        lineHeight: 0.92,
        letterSpacing: -0.01,
        transform: "uppercase",
        color: "#E0341F",
      },
      subtitle: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 600,
        size: 2.8,
        y: 0.89,
        letterSpacing: 0.24,
        transform: "uppercase",
        color: "#E8622A",
      },
    },
  },
  {
    id: "british-crime",
    name: "British Crime",
    genre: "Detective / cozy crime",
    description:
      "Ink-navy serif author over the skyline, then a tight stack of condensed white caps in the lower half. Classic UK detective series.",
    scrim: { scrim: "bottom", scrimColor: "#0B1524", scrimOpacity: 0.4 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 700,
        size: 2.2,
        y: 0.04,
        letterSpacing: 0.09,
        transform: "uppercase",
        color: "#16223C",
      },
      author: {
        ...CLEAN,
        fontId: "playfair",
        weight: 900,
        size: 9.5,
        y: 0.085,
        letterSpacing: 0.02,
        transform: "uppercase",
        color: "#16223C",
      },
      title: {
        ...CLEAN,
        fontId: "oswald",
        weight: 700,
        size: 13.5,
        y: 0.5,
        lineHeight: 0.94,
        letterSpacing: 0.01,
        transform: "uppercase",
        color: "#FFFFFF",
        shadowEnabled: true,
        shadowBlur: 22,
        shadowOffsetX: 0,
        shadowOffsetY: 4,
        shadowColor: "#0B1524",
        shadowOpacity: 0.55,
      },
      subtitle: {
        ...CLEAN,
        fontId: "oswald",
        weight: 300,
        size: 3,
        y: 0.93,
        letterSpacing: 0.2,
        transform: "uppercase",
        color: "#E6ECF3",
      },
    },
  },
  {
    id: "mass-market",
    name: "Mass Market",
    genre: "Bestseller paperback",
    description:
      "Cream caps top and bottom with an italic series line — the airport-carousel paperback, where the byline outranks everything.",
    scrim: { scrim: "both", scrimColor: "#0A0E0B", scrimOpacity: 0.45 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 700,
        size: 2.4,
        y: 0.035,
        letterSpacing: 0.08,
        transform: "uppercase",
        color: "#FFFFFF",
      },
      author: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 800,
        size: 11,
        y: 0.09,
        lineHeight: 0.96,
        letterSpacing: 0.01,
        transform: "uppercase",
        color: "#FFF8E7",
      },
      title: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 800,
        size: 11,
        y: 0.72,
        lineHeight: 0.96,
        letterSpacing: 0.01,
        transform: "uppercase",
        color: "#FFFFFF",
      },
      subtitle: {
        ...CLEAN,
        fontId: "lora",
        weight: 400,
        italic: true,
        size: 3.4,
        y: 0.9,
        letterSpacing: 0.06,
        transform: "none",
        color: "#F0E4C8",
      },
    },
  },

  /* ----------------------------------------------------------------
     Illustrated covers.

     Drawn artwork behaves differently from a photograph: the art is
     the selling point, so the type either turns out of its way (a
     vertical title down one edge) or leans into the illustration with
     flat vector letterforms, heavy outlines and no photographic scrim.
     ---------------------------------------------------------------- */

  {
    id: "graphic-novel",
    name: "Graphic Novel",
    genre: "Graphic novel / illustrated",
    description:
      "Title turned on its side down one edge in translucent display type, byline across the top, credits stacked at the foot. Keeps the artwork clear.",
    scrim: { scrim: "none", scrimColor: "#000000", scrimOpacity: 0.3 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 700,
        size: 2,
        y: 0.035,
        letterSpacing: 0.1,
        transform: "uppercase",
        color: "#1B2A52",
      },
      author: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 800,
        size: 6,
        y: 0.075,
        letterSpacing: 0.02,
        transform: "uppercase",
        color: "#16224A",
      },
      // Rotated a quarter turn: the block is laid out horizontally, then
      // spun about its own centre, so it reads bottom-to-top down the edge.
      title: {
        ...CLEAN,
        fontId: "playfair",
        weight: 900,
        size: 13,
        y: 0.36,
        width: 0.95,
        x: 0.78,
        rotation: -90,
        lineHeight: 1,
        letterSpacing: 0.01,
        transform: "none",
        color: "#2C3E75",
        opacity: 0.9,
      },
      subtitle: {
        ...CLEAN,
        fontId: "montserrat",
        weight: 700,
        size: 2.6,
        y: 0.88,
        letterSpacing: 0.16,
        transform: "uppercase",
        color: "#16224A",
      },
    },
  },
  {
    id: "storybook",
    name: "Storybook",
    genre: "Children's / picture book",
    description:
      "Brush-script title with a white keyline and soft shadow over the artwork, friendly rounded series flag above, byline in tracked caps below.",
    scrim: { scrim: "none", scrimColor: "#000000", scrimOpacity: 0.25 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "fredoka",
        weight: 600,
        size: 3,
        y: 0.05,
        letterSpacing: 0.14,
        transform: "uppercase",
        color: "#FFFFFF",
      },
      title: {
        ...CLEAN,
        fontId: "pacifico",
        weight: 400,
        size: 15,
        y: 0.13,
        lineHeight: 1.1,
        letterSpacing: 0,
        transform: "none",
        color: "#FFFFFF",
        // Warm keyline rather than a matching white one: the script has to
        // hold its shape over whatever the illustration is doing behind it.
        strokeWidth: 2.5,
        strokeColor: "#8A4212",
        shadowEnabled: true,
        shadowBlur: 12,
        shadowOffsetX: 2,
        shadowOffsetY: 5,
        shadowColor: "#7A3410",
        shadowOpacity: 0.45,
      },
      subtitle: {
        ...CLEAN,
        fontId: "fredoka",
        weight: 400,
        size: 3.2,
        y: 0.35,
        letterSpacing: 0.14,
        transform: "uppercase",
        color: "#FFFFFF",
      },
      author: {
        ...CLEAN,
        fontId: "fredoka",
        weight: 600,
        size: 4.2,
        y: 0.89,
        letterSpacing: 0.2,
        transform: "uppercase",
        color: "#FFFFFF",
      },
    },
  },
  {
    id: "middle-grade",
    name: "Middle Grade",
    genre: "Middle grade / early reader",
    description:
      "Fat rounded caps with a dark keyline — the chunky, high-contrast lettering that survives a school-library shelf and a thumbnail alike.",
    scrim: { scrim: "bottom", scrimColor: "#10233A", scrimOpacity: 0.3 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "fredoka",
        weight: 600,
        size: 2.8,
        y: 0.06,
        letterSpacing: 0.18,
        transform: "uppercase",
        color: "#FFD166",
      },
      title: {
        ...CLEAN,
        fontId: "baloo",
        weight: 800,
        size: 14,
        y: 0.13,
        lineHeight: 0.98,
        letterSpacing: 0.01,
        transform: "uppercase",
        color: "#FFFFFF",
        strokeWidth: 4,
        strokeColor: "#17324F",
        shadowEnabled: true,
        shadowBlur: 14,
        shadowOffsetX: 0,
        shadowOffsetY: 6,
        shadowColor: "#0A1A2C",
        shadowOpacity: 0.45,
      },
      subtitle: {
        ...CLEAN,
        fontId: "caveat",
        weight: 700,
        size: 5,
        y: 0.55,
        letterSpacing: 0,
        transform: "none",
        color: "#FFD166",
      },
      author: {
        ...CLEAN,
        fontId: "fredoka",
        weight: 700,
        size: 4.6,
        y: 0.87,
        letterSpacing: 0.12,
        transform: "uppercase",
        color: "#FFFFFF",
      },
    },
  },
  {
    id: "comic-book",
    name: "Comic Book",
    genre: "Comics / all-ages action",
    description:
      "Tilted comic lettering with a hard black outline and a colour drop, over a series flash. Panel-page energy on the shelf.",
    scrim: { scrim: "vignette", scrimColor: "#0A0A14", scrimOpacity: 0.4 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "bangers",
        weight: 400,
        size: 3.4,
        y: 0.06,
        letterSpacing: 0.1,
        transform: "uppercase",
        color: "#FFFFFF",
        bandEnabled: true,
        bandColor: "#E03A2F",
        bandOpacity: 1,
        bandPadX: 26,
        bandPadY: 12,
      },
      title: {
        ...CLEAN,
        fontId: "bangers",
        weight: 400,
        size: 17,
        y: 0.16,
        rotation: -4,
        lineHeight: 0.88,
        letterSpacing: 0.01,
        transform: "uppercase",
        color: "#FFD400",
        strokeWidth: 4.5,
        strokeColor: "#101014",
        shadowEnabled: true,
        shadowBlur: 0,
        shadowOffsetX: 4,
        shadowOffsetY: 7,
        shadowColor: "#E03A2F",
        shadowOpacity: 1,
      },
      subtitle: {
        ...CLEAN,
        fontId: "luckiest-guy",
        weight: 400,
        size: 3.6,
        y: 0.6,
        letterSpacing: 0.06,
        transform: "uppercase",
        color: "#FFFFFF",
        strokeWidth: 3,
        strokeColor: "#101014",
      },
      author: {
        ...CLEAN,
        fontId: "luckiest-guy",
        weight: 400,
        size: 4.4,
        y: 0.87,
        letterSpacing: 0.06,
        transform: "uppercase",
        color: "#FFFFFF",
        strokeWidth: 3,
        strokeColor: "#101014",
      },
    },
  },
  {
    id: "retro-deco",
    name: "Retro Deco",
    genre: "Retro / feel-good",
    description:
      "Rounded deco caps at wide tracking in warm brass, framed by a hairline. Jazz age, road trip, anything sunlit.",
    scrim: { scrim: "solid", scrimColor: "#2A1A10", scrimOpacity: 0.3 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "righteous",
        weight: 400,
        size: 2.6,
        y: 0.1,
        letterSpacing: 0.3,
        transform: "uppercase",
        color: "#F3E3C3",
      },
      title: {
        ...CLEAN,
        fontId: "righteous",
        weight: 400,
        size: 12,
        y: 0.2,
        lineHeight: 1.04,
        letterSpacing: 0.06,
        transform: "uppercase",
        color: "#F0C46A",
        rules: "both",
        ruleThickness: 3,
        ruleLength: 0.5,
        ruleGap: 40,
      },
      subtitle: {
        ...CLEAN,
        fontId: "pacifico",
        weight: 400,
        size: 5,
        y: 0.56,
        letterSpacing: 0,
        transform: "none",
        color: "#F3E3C3",
      },
      author: {
        ...CLEAN,
        fontId: "righteous",
        weight: 400,
        size: 4.2,
        y: 0.87,
        letterSpacing: 0.24,
        transform: "uppercase",
        color: "#F0C46A",
      },
    },
  },
  {
    id: "neon-tech",
    name: "Neon Tech",
    genre: "LitRPG / cyberpunk",
    description:
      "Squared techno caps carrying their own cyan glow, tracked wide and split by a rule. Built for dark, synthetic artwork.",
    scrim: { scrim: "both", scrimColor: "#03060F", scrimOpacity: 0.55 },
    roles: {
      series: {
        ...CLEAN,
        fontId: "orbitron",
        weight: 500,
        size: 2.4,
        y: 0.07,
        letterSpacing: 0.34,
        transform: "uppercase",
        color: "#41E8FF",
      },
      title: {
        ...CLEAN,
        fontId: "orbitron",
        weight: 900,
        size: 10,
        y: 0.17,
        lineHeight: 1.12,
        letterSpacing: 0.04,
        transform: "uppercase",
        color: "#FFFFFF",
        shadowEnabled: true,
        shadowBlur: 45,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        shadowColor: "#00D8FF",
        shadowOpacity: 0.95,
        rules: "below",
        ruleThickness: 2,
        ruleLength: 0.66,
        ruleGap: 40,
      },
      subtitle: {
        ...CLEAN,
        fontId: "orbitron",
        weight: 500,
        size: 2.8,
        y: 0.58,
        letterSpacing: 0.26,
        transform: "uppercase",
        color: "#9FD8E8",
      },
      author: {
        ...CLEAN,
        fontId: "orbitron",
        weight: 700,
        size: 3.8,
        y: 0.87,
        letterSpacing: 0.24,
        transform: "uppercase",
        color: "#FFFFFF",
      },
    },
  },
];

/**
 * Applies a preset to a layer. `custom` layers borrow the subtitle treatment —
 * they are almost always a strapline or an endorsement quote.
 */
export function styleForRole(
  style: CoverStyle,
  role: LayerRole
): RolePatch | undefined {
  return style.roles[role] ?? (role === "custom" ? style.roles.subtitle : undefined);
}
